### ISSUE TITLE
A component or helper named "simple-table" could not be found

### ISSUE THREAD

**Issue by shortthirdman** [Baltazore/ember-simple-table#3]
Browser console emitting error that {{#simple-table}} could not be found. Though it's installed through `ember install <addon-name>`.
Ember CLI: v2.11.1
Ember Simple Table: Baltazore/ember-simple-table#v0.10.4

**Comment by Baltazore** [comment]
Hello. Should be fixed by now. It was a strange typo after previous PR.

**Comment by shortthirdman** [comment]
Hi @Baltazore 
I solved it by using the correct version.
